# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/versus-project-192600/ping-app
  tag: 1.0.0
  pullPolicy: IfNotPresent
service:
  name: ping-app
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
ingress:
  enabled: false
resources: {}
