apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eleanorscoolapp 
  labels:
    app: eleanorscoolapp 
    environment: production
    anyotherlabel: something
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eleanorscoolapp 
  template:
    metadata:
      labels:
        app: eleanorscoolapp 
    spec:
      containers:
      - name: eleanorscoolapp 
        image: gcr.io/versus-project-192600/eleanorscoolapp:mytag
        ports:
          - containerPort: 3000
        command: ["ruby", "eleanorscoolapp.rb"]
