apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: <your-app-name>
  labels:
    app: <your-app-name>
    environment: production
    anyotherlabel: something
spec:
  replicas: 2
  selector:
    matchLabels:
      app: <your-app-name>
  template:
    metadata:
      labels:
        app: <your-app-name>
    spec:
      containers:
      - name: <your-app-name>
        image: gcr.io/versus-project-192600/<your-app-name>:<your-app-tag>
        ports:
          - containerPort: 3000
        command: ["ruby", "app.rb"]
