kind: Service
apiVersion: v1
metadata:
  name: eleanorscoolapp 
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: eleanorscoolapp 
  selector:
    app: eleanorscoolapp 
